name: ab_testing_example
description: An example Flutter project for the ab_testing package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  ab_testing_core:
    git:
      url: https://github.com/programmierbar/ab_testing.git
      ref: master
      path: core
  ab_testing_firebase:
    git:
      url: https://github.com/programmierbar/ab_testing.git
      ref: master
      path: firebase
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_remote_config: ^2.0.11
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true