name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ab_testing_core:
    path: ../core
  ab_testing_firebase:
    path: ../firebase
  firebase_core: ^1.19.1
  firebase_remote_config: ^2.0.11
  flutter_mobx: ^2.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true