include: package:lints/recommended.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_types_on_closure_parameters: true
    depend_on_referenced_packages: true
    noop_primitive_operations: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unnecessary_lambdas: true
    use_super_parameters: true
