name: ab_testing_core
description: A package for local a/b testing.
version: 0.8.1
homepage: https://github.com/programmierbar/ab_testing

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
