name: ab_testing_firebase
description: A package for remote a/b testing with the Firebase Remote Config.
publish_to: 'none'
version: 0.0.1
homepage: ''

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ab_testing_core:
    git:
      url: https://github.com/programmierbar/ab_testing.git
      ref: main
      path: core
  firebase_core: ^1.14.0
  firebase_remote_config: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:


