name: ab_testing_firebase
description: A package for remote a/b testing with the Firebase Remote Config.
version: 0.9.0
homepage: https://github.com/programmierbar/ab_testing

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ab_testing_core: ^0.9.0
  firebase_core: ^2.0.0
  firebase_remote_config: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:


